defaults: &defaults
  :mailchimp:
    :api_key: "bda7db4e058a2a53eff5da8494580cf7-us6"
    :timeout: 15
    :notify_on_unsubscribe: false
    :delete_on_unsubscribe: true
    :double_optin_on_subscribe: false
    :list_id_for_claimed_emails: "269048c8ea"

production:
  <<: *defaults

staging:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
