defaults: &defaults
  :mailchimp:
    :timeout: 15
    :notify_on_unsubscribe: false
    :delete_on_unsubscribe: true
    :double_optin_on_subscribe: false
    :list_id_for_claimed_emails: "f27201ce45"

production:
  <<: *defaults

staging:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
